import pathlib
import pyspark.sql.types

def register_library(spark: pyspark.sql.SparkSession) -> None: ...
def register_extra_library(spark: pyspark.sql.SparkSession, library_path: pathlib.Path, package_name: str) -> None: ...
def shutdown(spark: pyspark.sql.SparkSession) -> None: ...

class DBFSPath(pathlib.PosixPath):
    def __new__(self, *args, **kwargs): ...
    def as_dbfs(self) -> str: ...

def create_connection_string_for_synapse_db(host: str, database: str, user: str, password: str) -> str: ...
def create_jdbc_connection_string_for_synapse_db(host: str, database: str, user: str, password: str) -> str: ...
